environment:
  assembly_version: 3.0.0
  assembly_file_version: '$(assembly_version).$(appveyor_build_number)'
  assembly_informational_version: '$(assembly_file_version)'
  project_name: 'MvvmNavigation'
  solution_file_name: '$(project_name).sln'
  access_token:
    secure: 9NnzZ3Lxb6tEEXalTFO7eHW91jbsWpxeWyVQpWudDukFYr1oFvM7MIJvVBawcFJg

version: 'build-{build}'
skip_tags: true

only_commits:
  files:
    - code/
    - appveyor.yml
    
init:
# - cmd: appveyor UpdateBuild -Version %assembly_informational_version%
  - ps: appveyor UpdateBuild -Version $env:assembly_informational_version
  
dotnet_csproj:
  patch: true
  file: '**\*.props'
  version: '$(assembly_version)'
  file_version: '$(assembly_file_version)'
  informational_version: '$(assembly_informational_version)'

image: Visual Studio 2019
configuration: Release  

before_build:
  - nuget restore "./code/%solution_file_name%"

build:
  project: code\%solution_file_name%
  
test:
  assemblies:
    - '**\*Tests.dll'

artifacts:  
  - path: '**\*.nupkg'
    name: NuGet package
    
deploy:
  # Deploying to NuGet feed
  - provider: NuGet
    api_key:
      secure: eidVLC2fsvXQbz9RwM6yBkVQtlFjfpsaWPTwEcGZxVa2TOH7NbjaJyCIc2Blbcun
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master

on_success: 
  - ps: |
      if ($env:appveyor_repo_branch -eq 'master')
      {
        .\scripts\PushTag_AssemblyVersion_ToMaster.ps1
      }