version: 0.1.0.{build}

skip_tags: true

skip_commits:
  files:
    - '**/*.md'
    
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
before_build:
  - nuget restore "./src/UINavigation.sln"

image: Visual Studio 2017
platform: Any CPU
configuration: Release

environment:
  CODECOV_TOKEN: bbe39add-7bd2-4ba9-a132-ea9aa21b5ac9

build:
  project: src\UINavigation.sln
#  publish_nuget: true
  
test:
  assemblies:
    - '**\*.Tests.dll'
